---
title: "Paper 1: Vitis"
output: html_notebook
---

# Intro

The size and shape (physiognomy) of woody, dicotyledonous angiosperm leaves are correlated to climate.  These relationships have been used to develop paleoclimate proxies. Many plant communities, particularly in Northern Hemisphere temperate regions, have an inverse correlation between temperature and the degree of leaf dissection and the presence of teeth, as well as tooth size and abundance. One of the underlying assumptions of leaf physiognomic-paleoclimate proxies is that leaf traits can plastically respond to climate such that that leaves reliably track changes in temperature and precipitation.  Additionally, it is also assumed that leaf traits allometrically scale as a leaf matures through the growing season, such that juvenile and mature leaves have similar leaf traits. However, little work has been done to determine how quickly leaves plastically respond to changes in climate or whether all leaves on a plant respond in the same way. 

We used Digital Leaf Physiognomy (DiLP) to measure leaf characters of multiple *Vitis* species from two growing seasons with different temperatures and precipitation. The same vines were sampled each year in order to compare leaf shape on a vine-by-vine and leaf-by-leaf basis. 

```{r}
library(tidyverse)
library(readxl)
read_excel("R_DiLP_all_species.xlsx")
read_excel("R_DiLP_Vitis_all_added.xlsx")
```

# t-tests
First, we tested whether there were significant differences between the two growing seasons for each of the ratios measured, as well as the total number of teeth. To do this, we ran a series of t-tests. 

